export * from './Card/Skeleton';
export * from './Card/Card';
export * from './Header';
export * from './Categories';
export * from './Pagination/Pagination';
export * from './Sort';
export * from './CartItem';
export * from './CartEmpty';
export * from './Search/index';
export * from './NotFoundBlock/NotFoundBlock';

// export { default as Skeleton } from './Card/Skeleton';
// export { default as Card } from './Card/Card';
// export { default as Header } from './Header';
// export { default as Categories } from './Categories';
// export { default as Pagination } from './Pagination/Pagination';
// export { default as Sort } from './Sort';
// export { default as CartItem } from './CartItem';
// export { default as CartEmpty } from './CartEmpty';
// export { default as Search } from './Search/index';
// export { default as NotFoundBlock } from './NotFoundBlock/NotFoundBlock';
